mod_id=accelsticks
mod_version=1.0.0
mod_license=GPL-3.0
mod_authors=Yuuria
mod_description=Sticks that ticks!
mod_name=Acceleration Sticks

parchment_minecraftVersion=[VERSIONED]
parchment_mappingsVersion=[VERSIONED]

neo_version = [VERSIONED]
neo_version_range = [VERSIONED]
loader_version_range = [VERSIONED]

minecraft_version = [VERSIONED]
minecraft_version_range = [VERSIONED]